### ISSUE TITLE
any suggestion for web app to use with rest-mock?

### ISSUE THREAD

**Issue by glorylo** [francisrangel/rest-mock#1]
Hi I just noticed rest-mock and wanted to try writing something simple for it.  

since i am a bit new to java web app. development.. would something run rest-mock by creating a java application, or even subclassing restmock,  with a  'main' method that launches the server or will i need to create it using a framework that will run in some web container?  If the latter, can you suggest a maven archetype or tool chain.  a lot of the frameworks look heavy duty and i don't need even the database for now to get something 'faked' and up and running..

thanks a bunch

**Comment by gb** [comment]
Hey Glorylo, I don't know if I understand your question correctly but the ideia of rest-mock is quite simple:
Just create a main class and put your code inside.

When you do call to RestMock.startServer();
An embedded container will be initialized and you can access the URL. Ok?

We will provide an example app to make it clear ASAP.
Thank you for the interest.

**Comment by glorylo** [comment]
thanks for quick reply. i will experiment with it shortly and i'll provide feedback.

**Comment by francisrangel** [comment]
Hi Glorylo, I just created a new repo with a sample of rest-mock usage. I used JUnit and Selenium WebDriver to test a GET method, rendering a list on a html page.

Hope it helps: https://github.com/francisrangel/rest-mock-samples/tree/master/selenium

Although this example use selenium, it's not necessary. You could use rest-mock directly with JUnit or with a simple main class.

Thanks.

**Comment by glorylo** [comment]
Thanks Francis for the quick feedback.  I appreciate your help.

I just tried it with a main class with the simple: 

```
public static void main( String[] args )
{
   RestMock.startServer();
}
```

When I run my project as a Java application (mvn exec:java), I run into a couple of lines and it terminates.

2013-03-11 23:28:35.932:INFO::Logging to StdErrLog::DEBUG=false via org.eclipse.jetty.util.log.StdErrLog
2013-03-11 23:28:35.964:INFO::jetty-7.0.2.RC0

This is compiled for Java 1.6 and only dependency is rest-mock with the helper plugins to compile and run.

```
<dependencies>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>3.8.1</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>org</groupId>
        <artifactId>restmock</artifactId>
        <version>0.0.1</version>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>2.3.2</version>
            <configuration>
                <source>1.6</source>
                <target>1.6</target>
            </configuration>
        </plugin>

        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <configuration>
                <mainClass>ea.dre.RestTest</mainClass>
            </configuration>
        </plugin>

    </plugins>
</build>
```

I wonder if have you encounter something like this?  

Note:  I am also using Eclipse IDE w/ the maven plugin.

**Comment by gb** [comment]
Hey Glorylo,

Try put a while(true) { } after the RestMock.startServer().
It should fix your problem.
